### ISSUE TITLE
Selecting an Item to Associate an New Map with Throws an Exception

### ISSUE THREAD

**Issue by erochest** [scholarslab/NeatlineMaps#33]
Clicking "Select ->" beside an item gives this exception:

```
exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1' in /vagrant/omeka/application/libraries/Zend/Db/Statement/Mysqli.php:77
Stack trace:
#0 /vagrant/omeka/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT `item`.*...')
#1 /vagrant/omeka/application/libraries/Zend/Db/Adapter/Mysqli.php(381): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT `item`.*...')
#2 /vagrant/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(478): Zend_Db_Adapter_Mysqli->prepare('SELECT `item`.*...')
#3 /vagrant/omeka/application/libraries/Zend/Db/Adapter/Abstract.php(753): Zend_Db_Adapter_Abstract->query(Object(Zend_Db_Select), Array)
#4 [internal function]: Zend_Db_Adapter_Abstract->fetchRow(Object(Zend_Db_Select), Array)
#5 /vagrant/omeka/application/libraries/Omeka/Db.php(84): call_user_func_array(Array, Array)
#6 [internal function]: Omeka_Db->__call('fetchRow', Array)
#7 /vagrant/omeka/application/libraries/Omeka/Db/Table.php(501): Omeka_Db->fetchRow(Object(Zend_Db_Select), Array)
#8 /vagrant/omeka/plugins/NeatlineMaps/helpers/NeatlineMapsFunctions.php(327): Omeka_Db_Table->fetchObject(Object(Zend_Db_Select))
#9 /vagrant/omeka/plugins/NeatlineMaps/controllers/MapsController.php(190): _getSingleItem(NULL)
#10 /vagrant/omeka/application/libraries/Zend/Controller/Action.php(513): NeatlineMaps_MapsController->getserverAction()
#11 /vagrant/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('getserverAction')
#12 /vagrant/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#13 /vagrant/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#14 /vagrant/omeka/application/libraries/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#15 /vagrant/omeka/application/libraries/Omeka/Core.php(166): Zend_Application->run()
#16 /vagrant/omeka/admin/index.php(45): Omeka_Core->run()
#17 {main}
```

**Comment by erochest** [comment]
This was caused my invalid PHP config limiting the max POST size.
