### ISSUE TITLE
Where clause exception

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/NeatlineMaps#41]
On Omeka 1.5.1, using the master branch of the plugin, when I attempt to add a new server, a Zend exception is thrown. This is consistent whether or not the 'active' checkbox is ticked.

```
Zend_Db_Statement_Mysqli_Exception 
    - Mysqli prepare error: Unknown column 'active' in 'where clause'

#0 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Db/Statement.php(115): Zend_Db_Statement_Mysqli->_prepare('SELECT `n`.* FR...')
#1 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Db/Adapter/Mysqli.php(381): Zend_Db_Statement->__construct(Object(Zend_Db_Adapter_Mysqli), 'SELECT `n`.* FR...')
#2 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Db/Adapter/Abstract.php(478): Zend_Db_Adapter_Mysqli->prepare('SELECT `n`.* FR...')
#3 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Db/Adapter/Abstract.php(755): Zend_Db_Adapter_Abstract->query(Object(Omeka_Db_Select), Array)
#4 [internal function]: Zend_Db_Adapter_Abstract->fetchRow(Object(Omeka_Db_Select), Array)
#5 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Omeka/Db.php(83): call_user_func_array(Array, Array)
#6 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Omeka/Db/Table.php(500): Omeka_Db->__call('fetchRow', Array)
#7 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Omeka/Db/Table.php(500): Omeka_Db->fetchRow(Object(Omeka_Db_Select), Array)
#8 /Users/wsg4w/projects/NeatlineProjects/NeatlineMaps/models/NeatlineMapsServerTable.php(59): Omeka_Db_Table->fetchObject(Object(Omeka_Db_Select))
#9 /Users/wsg4w/projects/NeatlineProjects/NeatlineMaps/models/NeatlineMapsServer.php(93): NeatlineMapsServerTable->getActiveServer()
#10 /Users/wsg4w/projects/NeatlineProjects/NeatlineMaps/models/NeatlineMapsServerTable.php(42): NeatlineMapsServer->save()
#11 /Users/wsg4w/projects/NeatlineProjects/NeatlineMaps/controllers/ServersController.php(60): NeatlineMapsServerTable->updateServer(Object(NeatlineMapsServer), Array)
#12 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Controller/Action.php(516): NeatlineMaps_ServersController->addAction()
#13 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('addAction')
#14 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#15 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#16 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#17 /Applications/MAMP/htdocs/omeka-1.5.1/application/libraries/Omeka/Core.php(165): Zend_Application->run()
#18 /Applications/MAMP/htdocs/omeka-1.5.1/admin/index.php(44): Omeka_Core->run()
#19 {main}
```

**Comment by waynegraham** [comment]
I believe this is related to #42.
